### ISSUE TITLE
Plot is too big?

### ISSUE THREAD

**Issue by jianghaizhu** [spencerlyon2/PlotlyJS.jl#98] opened 2016-11-28 20:32 UTC
Here is a screenshot of a plot by Plots using PlotlyJS as backend. Notice the place where my arrow points to. The number of X axis showing in this little black box is not readable because it is outside of the window. I can resize my plot window so the number is more readable, some part of the black box is still blocked but the number is readable. Same thing happens in JUNO. However, I cannot fix it by resizing the plot panel in Atom. 

![1](https://cloud.githubusercontent.com/assets/16137435/20684824/b43dc350-b57f-11e6-9dd9-8f12bb3f3e95.png)

**Comment by spencerlyon2** [comment] 2016-11-28 20:47
Can you check if trying to create a similar plot using this package by itself (not through plots.jl) causes the same issue?

If it does not, the problem is almost certainly that @tbreloff will need to increase whatever he is currently using for layout.margin.{t,b,l,r}

**Comment by tbreloff** [comment] 2016-11-28 20:50
You can always set `bottom_margin`.  I'm not sure that I necessarily want to change the default margin due to this... I'd need to ponder it more.

**Comment by jianghaizhu** [comment] 2016-11-28 20:58
PlotlyJS alone doesn't have this problem. After increasing the `bottom_margin` in Plots, I can fix this problem. @tbreloff maybe you can set a better `bottom_margin` for this kind of plot when using PlotlyJS as backend?

**Comment by spencerlyon2** [comment] 2016-12-01 04:20
I think I'm going to close this as it isn't actually an issue over here.

If anyone objects, feel free to open back up

**Closed by spencerlyon2** 2016-12-01 04:20 UTC
