### ISSUE TITLE
Background not set?

### ISSUE THREAD

**Issue by tbreloff** [spencerlyon2/PlotlyJS.jl#36] opened 2016-04-21 19:20 UTC
When I do this:

```julia
using ExamplePlots; test_examples(:plotly, 13)
```
it brings up a browser window and the plot looks correct (tan background).  But if I do the same for the PlotlyJS backend, the background is white:

```julia
using ExamplePlots; test_examples(:plotlyjs, 13)
```

Any ideas why they would be different?  It should be the same JSON.

**Comment by spencerlyon2** [comment] 2016-04-21 20:17
Yep, I know _exactly_ what the problem is. When you try to set `paper_bgcolor=x` the PlotlyJS.jl underscore magic is applied and this gets applied and this is translated to `Dict(:paper => Dict(:bgcolor => x))` instead of `Dict(:paper_bgcolor => x)`

I'll take a look at the backend code in Plots.jl and see if I can fix this.

**Comment by spencerlyon2** [comment] 2016-04-21 20:29
Looks like you managed to hit on one of just a few trace attributes:

```
julia> using JSON

julia> d = JSON.parsefile(Pkg.dir("PlotlyJS", "deps", "plotschema.json"));

julia> get_keys(x) = [];

julia> get_keys(d::Associative) = vcat(collect(keys(d)), map(get_keys, values(d))...);

julia> unique(filter(x->contains(x, "_") && !(x[1] == '_'), get_keys(d["schema"]["traces"])))
5-element Array{Any,1}:
 "error_y"
 "error_x"
 "copy_ystyle"
 "copy_zstyle"
 "error_z"

julia> unique(filter(x->contains(x, "_") && !(x[1] == '_'), get_keys(d["schema"]["layout"])))
2-element Array{Any,1}:
 "plot_bgcolor"
 "paper_bgcolor"
```

I'm not really sure what the best way around this is. I noticed that you set the layout attributes using the `relayout!` methods, which is great. The problem with those is that they end up calling `setindex!`, which is where the underscore magic gets applied.

Any suggestions on an elegant way to deal with this? I think you should still use `relayout!`, but I should maybe add a kwarg to that function that describes if we should do the underscore replacing or just operate directly with the keys that were handed to us?

**Comment by spencerlyon2** [comment] 2016-04-21 20:35
Here's an idea...

What if arguments that are passed to `relayout!`s second argument in the dict are `merge`d with the underlying layout dict without any processing. But, we continue to do `_` processing for all attributes set via keyword arguments?

**Comment by tbreloff** [comment] 2016-04-21 20:43
Good catch!

> What if arguments that are passed to relayout!s second argument in the dict are merged with the underlying layout dict without any processing

This is the best option, if it doesn't break anything.

The other option is to keep a list `valid_keys` and only split if it's **not** in the list.

**Comment by spencerlyon2** [comment] 2016-04-21 21:08
OK fixed on my `sl/ijulia-comm` branch.

Will leave open here until we merge into master

**Comment by spencerlyon2** [comment] 2016-05-05 13:25
Done!

**Closed by spencerlyon2** 2016-05-05 13:25 UTC
